package ru.plumsoftware.theme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF004BE5)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF3567FF)
val onPrimaryContainerLight = Color(0xFFFFFCFF)
val secondaryLight = Color(0xFF495B9D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFA4B5FF)
val onSecondaryContainerLight = Color(0xFF334586)
val tertiaryLight = Color(0xFF9524AF)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFB243CA)
val onTertiaryContainerLight = Color(0xFFFFFCFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFAF8FF)
val onBackgroundLight = Color(0xFF191B24)
val surfaceLight = Color(0xFFFAF8FF)
val onSurfaceLight = Color(0xFF191B24)
val surfaceVariantLight = Color(0xFFE0E1F5)
val onSurfaceVariantLight = Color(0xFF434655)
val outlineLight = Color(0xFF737687)
val outlineVariantLight = Color(0xFFC3C5D8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3039)
val inverseOnSurfaceLight = Color(0xFFF0F0FC)
val inversePrimaryLight = Color(0xFFB7C4FF)
val surfaceDimLight = Color(0xFFD9D9E5)
val surfaceBrightLight = Color(0xFFFAF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F2FF)
val surfaceContainerLight = Color(0xFFEDEDFA)
val surfaceContainerHighLight = Color(0xFFE7E7F4)
val surfaceContainerHighestLight = Color(0xFFE2E1EE)

val primaryLightMediumContrast = Color(0xFF002B8E)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF295EF7)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF1E3172)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF5869AD)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF5F0073)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFFA93AC1)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFAF8FF)
val onBackgroundLightMediumContrast = Color(0xFF191B24)
val surfaceLightMediumContrast = Color(0xFFFAF8FF)
val onSurfaceLightMediumContrast = Color(0xFF0F1119)
val surfaceVariantLightMediumContrast = Color(0xFFE0E1F5)
val onSurfaceVariantLightMediumContrast = Color(0xFF323544)
val outlineLightMediumContrast = Color(0xFF4F5261)
val outlineVariantLightMediumContrast = Color(0xFF696C7D)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2E3039)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF0F0FC)
val inversePrimaryLightMediumContrast = Color(0xFFB7C4FF)
val surfaceDimLightMediumContrast = Color(0xFFC5C5D2)
val surfaceBrightLightMediumContrast = Color(0xFFFAF8FF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF3F2FF)
val surfaceContainerLightMediumContrast = Color(0xFFE7E7F4)
val surfaceContainerHighLightMediumContrast = Color(0xFFDCDCE8)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD1D1DD)

val primaryLightHighContrast = Color(0xFF002377)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF003BB9)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF112667)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF334586)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF4F0060)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF7E0097)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFAF8FF)
val onBackgroundLightHighContrast = Color(0xFF191B24)
val surfaceLightHighContrast = Color(0xFFFAF8FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE0E1F5)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF282B3A)
val outlineVariantLightHighContrast = Color(0xFF454858)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2E3039)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFB7C4FF)
val surfaceDimLightHighContrast = Color(0xFFB7B8C4)
val surfaceBrightLightHighContrast = Color(0xFFFAF8FF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF0F0FC)
val surfaceContainerLightHighContrast = Color(0xFFE2E1EE)
val surfaceContainerHighLightHighContrast = Color(0xFFD3D3E0)
val surfaceContainerHighestLightHighContrast = Color(0xFFC5C5D2)

val primaryDark = Color(0xFFB7C4FF)
val onPrimaryDark = Color(0xFF002681)
val primaryContainerDark = Color(0xFF3567FF)
val onPrimaryContainerDark = Color(0xFFFFFCFF)
val secondaryDark = Color(0xFFB7C4FF)
val onSecondaryDark = Color(0xFF172B6C)
val secondaryContainerDark = Color(0xFF304284)
val onSecondaryContainerDark = Color(0xFFA0B2FB)
val tertiaryDark = Color(0xFFF6ADFF)
val onTertiaryDark = Color(0xFF560068)
val tertiaryContainerDark = Color(0xFFB243CA)
val onTertiaryContainerDark = Color(0xFFFFFCFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF11131C)
val onBackgroundDark = Color(0xFFE2E1EE)
val surfaceDark = Color(0xFF11131C)
val onSurfaceDark = Color(0xFFE2E1EE)
val surfaceVariantDark = Color(0xFF434655)
val onSurfaceVariantDark = Color(0xFFC3C5D8)
val outlineDark = Color(0xFF8D90A1)
val outlineVariantDark = Color(0xFF434655)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E1EE)
val inverseOnSurfaceDark = Color(0xFF2E3039)
val inversePrimaryDark = Color(0xFF084EE8)
val surfaceDimDark = Color(0xFF11131C)
val surfaceBrightDark = Color(0xFF373942)
val surfaceContainerLowestDark = Color(0xFF0C0E16)
val surfaceContainerLowDark = Color(0xFF191B24)
val surfaceContainerDark = Color(0xFF1D1F28)
val surfaceContainerHighDark = Color(0xFF282933)
val surfaceContainerHighestDark = Color(0xFF33343E)

val primaryDarkMediumContrast = Color(0xFFD4DBFF)
val onPrimaryDarkMediumContrast = Color(0xFF001D68)
val primaryContainerDarkMediumContrast = Color(0xFF6989FF)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFD4DBFF)
val onSecondaryDarkMediumContrast = Color(0xFF071F61)
val secondaryContainerDarkMediumContrast = Color(0xFF7C8DD4)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFCCDFF)
val onTertiaryDarkMediumContrast = Color(0xFF450054)
val tertiaryContainerDarkMediumContrast = Color(0xFFD261E9)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF11131C)
val onBackgroundDarkMediumContrast = Color(0xFFE2E1EE)
val surfaceDarkMediumContrast = Color(0xFF11131C)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF434655)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD9DBEE)
val outlineDarkMediumContrast = Color(0xFFAFB1C3)
val outlineVariantDarkMediumContrast = Color(0xFF8D8FA1)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE2E1EE)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF282A33)
val inversePrimaryDarkMediumContrast = Color(0xFF003AB7)
val surfaceDimDarkMediumContrast = Color(0xFF11131C)
val surfaceBrightDarkMediumContrast = Color(0xFF42444E)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF05070F)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1B1D26)
val surfaceContainerDarkMediumContrast = Color(0xFF262731)
val surfaceContainerHighDarkMediumContrast = Color(0xFF30323C)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3C3D47)

val primaryDarkHighContrast = Color(0xFFEEEFFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFB1C0FF)
val onPrimaryContainerDarkHighContrast = Color(0xFF00072B)
val secondaryDarkHighContrast = Color(0xFFEEEFFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFB1C0FF)
val onSecondaryContainerDarkHighContrast = Color(0xFF00072B)
val tertiaryDarkHighContrast = Color(0xFFFFEAFC)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFF4A7FF)
val onTertiaryContainerDarkHighContrast = Color(0xFF1A0022)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF11131C)
val onBackgroundDarkHighContrast = Color(0xFFE2E1EE)
val surfaceDarkHighContrast = Color(0xFF11131C)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF434655)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEEEFFF)
val outlineVariantDarkHighContrast = Color(0xFFBFC1D4)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE2E1EE)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF003AB7)
val surfaceDimDarkHighContrast = Color(0xFF11131C)
val surfaceBrightDarkHighContrast = Color(0xFF4E4F5A)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1D1F28)
val surfaceContainerDarkHighContrast = Color(0xFF2E3039)
val surfaceContainerHighDarkHighContrast = Color(0xFF393B45)
val surfaceContainerHighestDarkHighContrast = Color(0xFF454650)

val md_theme_light_success = Color(0xFFCDEDA3)
val md_theme_light_onSuccess = Color(0xFF5aad07)

val md_theme_dark_success = Color(0xFF354E16)
val md_theme_dark_onSuccess = Color(0xFFCDEDA3)

internal val lightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
)

internal val darkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
)

fun Color.disabled() : Color = this.copy(alpha = 0.5f)
